package org.cvit.cabig.dmr.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class DmrConfiguration implements ServiceConfiguration {

	public static DmrConfiguration  configuration = null;

	public static DmrConfiguration getConfiguration() throws Exception {
		if (DmrConfiguration.configuration != null) {
			return DmrConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			DmrConfiguration.configuration = (DmrConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return DmrConfiguration.configuration;
	}
	
	private String etcDirectoryPath;
	
	
	private String queryProcessorClass;
	
	private String sdk4Style_beansJarFileName;
	
	private String cqlQueryProcessorConfig_applicationName;
	
	private String serverConfigLocation;
	
	private String dataService_cqlValidatorClass;
	
	private String dataService_domainModelValidatorClass;
	
	private String dataService_validateCqlFlag;
	
	private String dataService_validateDomainModelFlag;
	
	private String dataService_classMappingsFilename;
	
	private String anzo_properties;
	
	private String cqlQueryProcessorConfig_database_password;
	
	private String cqlQueryProcessorConfig_database_url;
	
	private String cqlQueryProcessorConfig_database_type;
	
	private String cqlQueryProcessorConfig_user;
	
	private String cqlQueryProcessorConfig_password;
	
	private String cqlQueryProcessorConfig_database_user;
	
	
	public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}

	
	public String getQueryProcessorClass() {
		return queryProcessorClass;
	}
	
	
	public void setQueryProcessorClass(String queryProcessorClass) {
		this.queryProcessorClass = queryProcessorClass;
	}

	
	public String getSdk4Style_beansJarFileName() {
		return sdk4Style_beansJarFileName;
	}
	
	
	public void setSdk4Style_beansJarFileName(String sdk4Style_beansJarFileName) {
		this.sdk4Style_beansJarFileName = sdk4Style_beansJarFileName;
	}

	
	public String getCqlQueryProcessorConfig_applicationName() {
		return cqlQueryProcessorConfig_applicationName;
	}
	
	
	public void setCqlQueryProcessorConfig_applicationName(String cqlQueryProcessorConfig_applicationName) {
		this.cqlQueryProcessorConfig_applicationName = cqlQueryProcessorConfig_applicationName;
	}

	
	public String getServerConfigLocation() {
		return ContainerConfig.getBaseDirectory() + File.separator + serverConfigLocation;
	}
	
	
	public void setServerConfigLocation(String serverConfigLocation) {
		this.serverConfigLocation = serverConfigLocation;
	}

	
	public String getDataService_cqlValidatorClass() {
		return dataService_cqlValidatorClass;
	}
	
	
	public void setDataService_cqlValidatorClass(String dataService_cqlValidatorClass) {
		this.dataService_cqlValidatorClass = dataService_cqlValidatorClass;
	}

	
	public String getDataService_domainModelValidatorClass() {
		return dataService_domainModelValidatorClass;
	}
	
	
	public void setDataService_domainModelValidatorClass(String dataService_domainModelValidatorClass) {
		this.dataService_domainModelValidatorClass = dataService_domainModelValidatorClass;
	}

	
	public String getDataService_validateCqlFlag() {
		return dataService_validateCqlFlag;
	}
	
	
	public void setDataService_validateCqlFlag(String dataService_validateCqlFlag) {
		this.dataService_validateCqlFlag = dataService_validateCqlFlag;
	}

	
	public String getDataService_validateDomainModelFlag() {
		return dataService_validateDomainModelFlag;
	}
	
	
	public void setDataService_validateDomainModelFlag(String dataService_validateDomainModelFlag) {
		this.dataService_validateDomainModelFlag = dataService_validateDomainModelFlag;
	}

	
	public String getDataService_classMappingsFilename() {
		return ContainerConfig.getBaseDirectory() + File.separator + dataService_classMappingsFilename;
	}
	
	
	public void setDataService_classMappingsFilename(String dataService_classMappingsFilename) {
		this.dataService_classMappingsFilename = dataService_classMappingsFilename;
	}

	
	public String getAnzo_properties() {
		return ContainerConfig.getBaseDirectory() + File.separator + anzo_properties;
	}
	
	
	public void setAnzo_properties(String anzo_properties) {
		this.anzo_properties = anzo_properties;
	}

	
	public String getCqlQueryProcessorConfig_database_password() {
		return cqlQueryProcessorConfig_database_password;
	}
	
	
	public void setCqlQueryProcessorConfig_database_password(String cqlQueryProcessorConfig_database_password) {
		this.cqlQueryProcessorConfig_database_password = cqlQueryProcessorConfig_database_password;
	}

	
	public String getCqlQueryProcessorConfig_database_url() {
		return cqlQueryProcessorConfig_database_url;
	}
	
	
	public void setCqlQueryProcessorConfig_database_url(String cqlQueryProcessorConfig_database_url) {
		this.cqlQueryProcessorConfig_database_url = cqlQueryProcessorConfig_database_url;
	}

	
	public String getCqlQueryProcessorConfig_database_type() {
		return cqlQueryProcessorConfig_database_type;
	}
	
	
	public void setCqlQueryProcessorConfig_database_type(String cqlQueryProcessorConfig_database_type) {
		this.cqlQueryProcessorConfig_database_type = cqlQueryProcessorConfig_database_type;
	}

	
	public String getCqlQueryProcessorConfig_user() {
		return cqlQueryProcessorConfig_user;
	}
	
	
	public void setCqlQueryProcessorConfig_user(String cqlQueryProcessorConfig_user) {
		this.cqlQueryProcessorConfig_user = cqlQueryProcessorConfig_user;
	}

	
	public String getCqlQueryProcessorConfig_password() {
		return cqlQueryProcessorConfig_password;
	}
	
	
	public void setCqlQueryProcessorConfig_password(String cqlQueryProcessorConfig_password) {
		this.cqlQueryProcessorConfig_password = cqlQueryProcessorConfig_password;
	}

	
	public String getCqlQueryProcessorConfig_database_user() {
		return cqlQueryProcessorConfig_database_user;
	}
	
	
	public void setCqlQueryProcessorConfig_database_user(String cqlQueryProcessorConfig_database_user) {
		this.cqlQueryProcessorConfig_database_user = cqlQueryProcessorConfig_database_user;
	}

	
}
